# Default/Common Configuration
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # Internationalization
  messages:
    basename: i18n/messages_ja
    encoding: UTF-8
    fallback-to-system-locale: false
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB