# Development Environment Configuration

# Server Configuration
server:
  port: 8080

# Database Configuration - H2 for development
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # SQL Initialization
  sql:
    init:
      mode: always
      platform: h2
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console
  h2:
    console:
      enabled: true
  
  # Thymeleaf Configuration
  thymeleaf:
    cache: false

# Logging
logging:
  level:
    com.example.tabledef: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE