version: '3.8'

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: tabledef-postgres-dev
    environment:
      POSTGRES_DB: tabledef_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  postgres-dev-data: